version: '3'

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      PYTHONPATH: /workspace
    tty: true
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - '5001:80'
